name: Build Components
on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          npm i -g npm
          npm ci --ignore-scripts --legacy-peer-deps
          npm rebuild && npm run prepare --if-present
          npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Updated Components
        run: npm run build:since -- --base=${{ github.event.pull_request.base.sha }} --head=${{github.event.pull_request.head.sha}}
