
name: Try to get forked commits
on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: getPrUrl
        id: pr-url
        uses: ammaratef45/pr-url-action@v1
      - name: display
        run: echo ${{ steps.pr-url.outputs.url }}
#       - uses: actions/setup-node@v3
#         with:
#           node-version-file: '.nvmrc'
#           cache: 'npm'
#           registry-url: 'https://packages.aa.com/artifactory/api/npm/npm-public/'
      - run: |
          echo "Check for stuff"
          echo base.sha => ${{ github.event.pull_request.base.sha }}
          echo head.sha => ${{github.event.pull_request.head.sha}}
          echo actor => ${{github.actor}}
          echo github.repositoryUrl => ${{github.repositoryUrl}}
          echo github.event.pull_request.head.repositoryUrl => ${{github.event.pull_request.head.repositoryUrl}} 
          echo github.event.pull_request.repositoryUrl => ${{github.event.pull_request.repositoryUrl}} 
          
          	
          	
#       - run: |
#           npm i -g npm
#           npm ci --ignore-scripts --legacy-peer-deps
#           npm rebuild && npm run prepare --if-present
#           npm run bootstrap
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#       - name: Build Updated Components
#         run: npm run build:since -- --base=${{ github.event.pull_request.base.sha }} --head=${{github.event.pull_request.head.sha}}
